
class Alocations {
  final String rooms;
  final String names;

  Alocations(this.rooms, this.names);
  Alocations.fromJson(Map<String, dynamic> json)
      : rooms = json['rooms'],
        names = json['names'];
  Map<String, dynamic> toJson() => {
        'rooms': [
          "LT",
          "RMA",
          "RMB",
          "206",
          "303",
          "304",
          "LH",
          "VSLA",
          "PB001",
          "PB020",
          "PB014",
          "PB012",
          "PB008",
          "PB201",
          "PB214",
          "PB212",
          "PB208",
          "N1",
          "N2",
          "VCR",
          "ECR",
          "EA",
          "A110",
          "FOSSB4",
          "FOSSB3",
          "FOSSGF9",
          "FOSSGF8"
        ],
        'names': [
          "Alfred Crabbe AE",
          "Benjamin Asare CHE",
          "Elvis Yeboah",
          "Ezekiel Nettey-Oppong MSE",
          "Franklin Bartels EE ",
          "Ignace Kodjo CHE",
          "Jephter Fordjour CE ",
          "Justice Kwamena COE / Janet Baffoe",
          "Komla Wilson COE / Etornam Tsyaw",
          "Godson Nyaforkpa MSE / Alice Kwateng EE",
          "Nana Ofosu Asante EE / Constance Adomako",
          "Opoku-Mensah GEOM / Owusu Sarpong",
          "Oppong Kyekyeku AE",
          "Solomon Apafo CE / Edwina Ampadu CHE",
          "Elijah Effah MSE / Deborah Adoma",
          "Awudu Yussif EE / Obed Asare GEOM",
          "Courage Jahmon GEOM / Victor Elikem CoE",
          "Fortunatus TELE",
          "Israel Mark ME",
          "Micheal Etorko PETE",
          "Prince Henry METE",
          "Mohammed Abdul-Jaleel METE / Freda Quaye MSE",
          "Opoku Clement METE / Anita Broni AE",
          "Isaac Owusu Dapaah MSE / Kanyomse Albright EE / Eric Asante",
          "Lord Wiafe EE / Ahmed Abdul Nasir MSE ",
          "Joshua Adu MSE / Micheal Coleman ME / Enoch Aning GEOM",
          "Jacklingo Quansah COE / Kobena Badu EE / Aduamah Isaac"
        ],
        /*
        "LT": "Alfred Crabbe AE",
        "RMA": "Benjamin Asare CHE",
        "RMB": "Elvis Yeboah",
        "206": "Ezekiel Nettey-Oppong MSE",
        "303": "Franklin Bartels EE ",
        "304": "Ignace Kodjo CHE",
        "LH": "Jephter Fordjour CE ",
        "VSLA": "Justice Kwamena COE / Janet Baffoe",
        "PB001": "Komla Wilson COE / Etornam Tsyaw",
        "PB020": "Godson Nyaforkpa MSE / Alice Kwateng EE",
        "PB014": "Nana Ofosu Asante EE / Constance Adomako",
        "PB012": "Opoku-Mensah GEOM / Owusu Sarpong",
        "PB008": "Oppong Kyekyeku AE",
        "PB201": "Solomon Apafo CE / Edwina Ampadu CHE",
        "PB214": "Elijah Effah MSE / Deborah Adoma",
        "PB212": "Awudu Yussif EE / Obed Asare GEOM",
        "PB208": "Courage Jahmon GEOM / Victor Elikem CoE",
        "N1": "Fortunatus TELE",
        "N2": "Israel Mark ME",
        "VCR": "Micheal Etorko PETE",
        "ECR": "Prince Henry METE",
        "EA": "Mohammed Abdul-Jaleel METE / Freda Quaye MSE",
        "A110": "Opoku Clement METE / Anita Broni AE",
        "FOSSB4": "Isaac Owusu Dapaah MSE / Kanyomse Albright EE / Eric Asante",
        "FOSSB3": "Lord Wiafe EE / Ahmed Abdul Nasir MSE ",
        "FOSSGF9": "Joshua Adu MSE / Micheal Coleman ME / Enoch Aning GEOM",
        "FOSSGF8": "Jacklingo Quansah COE / Kobena Badu EE / Aduamah Isaac"
        */
      };
}
